export const collectionTemplate = (UID) => {
  return {
    collectionInfo: {
      archived: false,
      UID: UID,
      collectionName: "🎴 Nouvelle Collection",
      resolution: 60,
      elementFormat: "pokerCard",
      pageFormat: "A4",
      pageOrientation: "portrait",
      visualGuide: "center",
      W: 100,
      H: 100,
      pageWidth: 100,
      pageHeight: 100,
      lastComponentIndex: 0,
      lastElementIndex: 0,
      lastAssetIndex: 0,
      maxElementQty: 52,
      pageExportFormat: "jpg",
      cuttingHelp: false,
      lastSavingTime: Date.now(),
    },
    template: [],
    elements: {
      headers: [],
      data: [],
    },
  };
};

export const projectTemplate = (UID) => {
  return { UID: UID, projectName: "🎲 Nouveau Projet", lastSavingTime: Date.now(), archived: false };
};

export let shapeComponentTemplate = {
  UID: 0,
  isVisible: true,
  component: "SHAPE",
  componentName: { value: "NOUVELLE FORME" },
  src: { value: "ring", type: "0" },
  positionX: { value: ":0.5*W", type: "0" },
  positionY: { value: ":0.5*H", type: "0" },
  width: { value: "100", type: "0" },
  height: { value: "100", type: "0" },
  anchor: { value: ":CENTER", type: "0" },
  angle: { value: "0", type: "0" },
  color: { value: "#DDDDDD", type: "0" },
  opacity: { value: "1", type: "0" },
  borderColor: { value: "#FF00FF", type: "0" },
  borderOpacity: { value: "1", type: "0" },
  borderWeight: { value: "3", type: "0" },
  shadowColor: { value: "#000000", type: "0" },
  shadowOffsetX: { value: "5", type: "0" },
  shadowOffsetY: { value: "5", type: "0" },
  shadowOpacity: { value: "0", type: "0" },
};

export let textComponentTemplate = {
  UID: 0,
  isVisible: true,
  component: "TEXT",
  componentName: { value: "NOUVEAU TEXTE" },
  src: { value: "nouveau texte", type: "0" },
  positionX: { value: ":0.5*W", type: "0" },
  positionY: { value: ":0.5*H", type: "0" },
  maxWidth: { value: ":W", type: "0" },
  textAnchorHori: { value: ":CENTER", type: "0" },
  textAnchorVert: { value: ":CENTER", type: "0" },
  interline: { value: "1", type: "0" },
  inlineImgsSize: { value: "50", type: "0" },
  inlineImgsXOffset: { value: "0", type: "0" },
  color: { value: "#000000", type: "0" },
  size: { value: "3", type: "0" },
  font: { value: "Verdana", type: "0" },
  angle: { value: "0", type: "0" },
  opacity: { value: "1", type: "0" },
  shadowColor: { value: "#000000", type: "0" },
  shadowOffsetX: { value: "5", type: "0" },
  shadowOffsetY: { value: "5", type: "0" },
  shadowOpacity: { value: "0", type: "0" },
};

export let titleComponentTemplate = {
  UID: 0,
  isVisible: true,
  component: "TITLE",
  componentName: { value: "TITRE" },
  src: { value: "nouveau titre", type: "0" },
  positionX: { value: ":0.5*W", type: "0" },
  titleWidth: { value: ":W*0.8", type: "0" },
  maxSize: { value: "5", type: "0" },
  positionY: { value: ":0.1*H", type: "0" },
  color: { value: "#000000", type: "0" },
  font: { value: "Verdana", type: "0" },
  angle: { value: "0", type: "0" },
  opacity: { value: "1", type: "0" },
  shadowColor: { value: "#000000", type: "0" },
  shadowOffsetX: { value: "5", type: "0" },
  shadowOffsetY: { value: "5", type: "0" },
  shadowOpacity: { value: "0", type: "0" },
};

export let imageComponentTemplate = {
  UID: 0,
  isVisible: true,
  component: "IMAGE",
  componentName: { value: "NOUVELLE IMAGE" },
  src: { value: "ressource à afficher", type: "0" },
  positionX: { value: ":0.5*W", type: "0" },
  positionY: { value: ":0.5*H", type: "0" },
  width: { value: "100", type: "0" },
  height: { value: "100", type: "0" },
  anchor: { value: ":CENTER", type: "0" },
  opacity: { value: "1", type: "0" },
  tint: { value: "#ffffff", type: "0" },
  angle: { value: "0", type: "0" },
  listAnchor: { value: ":CENTER", type: "0" },
  spacingX: { value: "0", type: "0" },
  spacingY: { value: "0", type: "0" },
  style: { value: "straight", type: "0" },
  offsetX: { value: "0", type: "0" },
  offsetY: { value: "0", type: "0" },
  shadowColor: { value: "#000000", type: "0" },
  shadowOffsetX: { value: "5", type: "0" },
  shadowOffsetY: { value: "5", type: "0" },
  shadowOpacity: { value: "0", type: "0" },
};
